export { registerDoctorCommand } from './doctor'
export { registerInitCommand } from './init'
export { registerInstallCommand } from './install'
export { registerListCommand } from './list'
export { registerUninstallCommand } from './uninstall'
