export type { EmbeddedContext, InstallInput, InstallResult } from './types'
export { installSkillFlow } from './install-skill'
export { installSkillsetFlow } from './install-skillset'
export { pruneUnchanged } from './prune-unchanged'
export { buildInstructions } from './shared'
export { spawnClaude } from './spawn-claude'
